new state('Alabama,'US-AL,'Alabama,'01'),
new state('Alaska,'US-AK,Alaska,'02'),
new state('Arizona,'US-AZ,Arizona,'04'),
new state('Arkansas,'US-AR,Arkansas,'05'),
new state('California,'US-CA,California,'06'),
new state('Colorado,'US-CO,Colorado,'08'),
new state('Connecticut,'US-CT,Connecticut,'09'),
new state('Delaware,'US-DE,Delaware,'10'),
new state('District of Columbia,'US-DC,District of Columbia,'11'),
new state('Florida,'US-FL,Florida,'12'),
new state('Georgia,'US-GA,Georgia,'13'),
new state('Hawaii,'US-HI,Hawaii,'15'),
new state('Idaho,'US-ID,Idaho,'16'),
new state('Illinois,'US-IL,Illinois,'17'),
new state('Indiana,'US-IN,Indiana,'18'),
new state('Iowa,'US-IA,Iowa,'19'),
new state('Kansas,'US-KS,Kansas,'20'),
new state('Kentucky,'US-KY,Kentucky,'21'),
new state('Louisiana,'US-LA,Louisiana,'22'),
new state('Maine,'US-ME,Maine,'23'),
new state('Maryland,'US-MD,Maryland,'24'),
new state('Massachusetts,'US-MA,Massachusetts,'25'),
new state('Michigan,'US-MI,Michigan,'26'),
new state('Minnesota,'US-MN,Minnesota,'27'),
new state('Mississippi,'US-MS,Mississippi,'28'),
new state('Missouri,'US-MO,Missouri,'29'),
new state('Montana,'US-MT,Montana,'30'),
new state('Nebraska,'US-NE,Nebraska,'31'),
new state('Nevada,'US-NV,Nevada,'32'),
new state('New Hampshire,'US-NH,New Hampshire,'33'),
new state('New Jersey,'US-NJ,New Jersey,'34'),
new state('New Mexico,'US-NM,New Mexico,'35'),
new state('New York,'US-NY,New York,'36'),
new state('North Carolina,'US-NC,North Carolina,'37'),
new state('North Dakota,'US-ND,North Dakota,'38'),
new state('Ohio,'US-OH,Ohio,'39'),
new state('Oklahoma,'US-OK,Oklahoma,'40'),
new state('Oregon,'US-OR,Oregon,'41'),
new state('Pennsylvania,'US-PA,Pennsylvania,'42'),
new state('Puerto Rico,'US-PR,Puerto Rico,'72'),
new state('Rhode Island,'US-RI,Rhode Island,'44'),
new state('South Carolina,'US-SC,South Carolina,'45'),
new state('South Dakota,'US-SD,South Dakota,'46'),
new state('Tennessee,'US-TN,Tennessee,'47'),
new state('Texas,'US-TX,Texas,'48'),
new state('Utah,'US-UT,Utah,'49'),
new state('Vermont,'US-VT,Vermont,'50'),
new state('Virginia,'US-VA,Virginia,'51'),
new state('Virgin Islands,'US-VI,Virgin Islands,'78'),
new state('Washington,'US-WA,Washington,'53'),
new state('West Virginia,'US-WV,West Virginia,'54'),
new state('Wisconsin,'US-WI,Wisconsin,'55'),
new state('Wyoming,'US-WY,Wyoming,'56'),
